### ISSUE TITLE
Timeouts 

### ISSUE THREAD

**Issue by Sineos** [KoljaWindeler/kaco#9]
## Version of the custom_component
0.5.1

## Configuration

* All polling options activated
* Poll times default 20 / 120

## Describe the bug
Basically the component works fine but I have a lot of the above entries in my log.
Whenever I try to access the WebIF it works. I know the WebIF is slow as hell and refreshing it like 3 times shortly in a row will make it crash.

Is there a way to increase the timeout?

## Debug log

```text

2022-08-23 20:40:12.270 ERROR (MainThread) [custom_components.kaco] Timeout fetching kaco_192.168.178.14 data
2022-08-23 20:40:42.256 WARNING (MainThread) [custom_components.kaco] KACO Panel with IP 192.168.178.14 doesn't answer

```

**Comment by mickeyreg** [comment]
Hi,

I've changed in **/root/config/custom_components/kaco/__init\__.py**:
- in line 108 timeout to 15: https://github.com/KoljaWindeler/kaco/blob/964fda87a3136adeae72ee8b10dc141168626fc0/custom_components/kaco/__init__.py#L108
- and in line 141 timeout to 60: https://github.com/KoljaWindeler/kaco/blob/964fda87a3136adeae72ee8b10dc141168626fc0/custom_components/kaco/__init__.py#L141

The second change was particularly important because I measured it and time to download daily data with wget was 36 seconds.
After HA restart the inverter was recognized.

Regards,
Mickey
